"""HYROX Level 2 "Mastering Performance" Coach Assessment — question bank.

AUTO-GENERATED by ``app/backend/prep_hyrox_assessment_questions.py`` from
``hyrox-files/HYROX_L2_QuestionBank_Final.xlsx`` (master tab "Module 1"). Do not edit by hand —
re-run the generator. This is the single source of truth for the assessment rubric and is compiled
into the system prompt at import time by sampleprompt.py, so the grader always has the exact rubric
for the asked question on every (stateless) turn. Do NOT index this into Azure Search.

The 52 questions are grouped into 13 modules (M1..M6, M7.1..M7.4, M8..M10), asked in order. Each
module is scored separately at an 80% threshold; the per-key-point verdict drives scoring (one point
per key point, capped at ``max_pts``; ``len(key_points) == max_pts`` for every question).

Each question dict:
  number              int    1..52, fixed module/ask order; the id used in [[SCORE]]/[[ASKED]] markers
  module              str    module key, e.g. "M7.1"
  qid                 str    client display id, e.g. "M7.1-Q03" (audit/logging only)
  question            str    the prompt shown to the learner
  primary_answer      str    full model answer (reference only; never revealed early)
  alternative_answer  str    an accepted alternative phrasing (reference only; grading aid)
  key_points          list   each entry = 1 semantic point the learner must supply (1 point each)
  max_pts             int    cap for this question (== len(key_points))
"""

from typing import Optional, TypedDict


class AssessmentQuestion(TypedDict):
    number: int
    module: str
    qid: str
    question: str
    primary_answer: str
    alternative_answer: str
    key_points: list[str]
    max_pts: int


QUESTIONS: list[AssessmentQuestion] = [
    {
        "number": 1,
        "module": 'M1',
        "qid": 'M1-Q01',
        "question": "What is the difference between 'reflection in action' and 'reflection on action,' and why does a HYROX coach need both?",
        "primary_answer": 'Reflection in action is the practice of adjusting coaching decisions in real time during a session. The coach notices that something is not working and changes approach immediately. Reflection on action happens after the session or competition ends. The coach revisits what occurred, analyses the decisions made, and draws lessons to improve future practice. A HYROX coach needs both because real-time adjustment keeps the session on track and athletes safe, while post-session review drives long-term development as a coach.',
        "alternative_answer": 'In-session responsiveness when things are not going as planned is reflection in action. Stepping back after the fact to ask what worked, what did not, and what to change next time is reflection on action. One improves the immediate session; the other builds the coach over time.',
        "key_points": [
            'Reflection in action defined',
            'Reflection on action defined',
            'Why both matter',
        ],
        "max_pts": 3,
    },
    {
        "number": 2,
        "module": 'M1',
        "qid": 'M1-Q02',
        "question": "Describe what a 'growth mindset' means for a HYROX coach, and give two examples of how it differs from a fixed mindset in practice.",
        "primary_answer": "A growth mindset, introduced by Dr. Carol Dweck, is the belief that abilities and intelligence can be developed through dedication, effort, and learning. A HYROX coach with a growth mindset treats mistakes as useful data rather than evidence of failure, and actively seeks out new knowledge as the sport evolves. In practice: a growth-minded coach whose athlete hits a performance plateau looks for new methods or seeks input from specialists. A fixed-mindset coach assumes the plateau reflects the athlete's ceiling. Similarly, a growth-minded coach updates their programming as HYROX research develops; a fixed-mindset coach relies only on what they knew at certification.",
        "alternative_answer": 'The growth mindset principle from Carol Dweck holds that talent and skill are not fixed traits. A coach with this mindset stays curious, welcomes challenges, and treats failures as learning opportunities. Practically, they adjust their methods when something stops working rather than blaming the athlete, and they keep learning as HYROX develops rather than assuming their initial training was sufficient.',
        "key_points": [
            'Growth mindset: belief that abilities develop through effort',
            'Fixed vs. growth contrast',
            'Practical coaching example',
        ],
        "max_pts": 3,
    },
    {
        "number": 3,
        "module": 'M1',
        "qid": 'M1-Q03',
        "question": 'Why is a growth mindset especially important for coaches in an emerging sport like HYROX compared to a well-established sport?',
        "primary_answer": 'In a well-established sport, decades of research, standardised best practices, and validated training systems exist for coaches to draw from. In HYROX, the sport is still evolving rapidly: training methods, race strategy, athlete profiling, and performance science are all still being developed. A coach who assumes their current knowledge is complete will fall behind as the sport changes. A growth mindset keeps the coach in a state of active learning, curiosity about new developments, and willingness to revise their approach as better information becomes available.',
        "alternative_answer": 'Established sports have fixed frameworks coaches can follow with confidence. HYROX does not have that yet. The coaches who succeed long-term in HYROX will be those who treat their knowledge as a starting point and keep developing it, not those who treat certification as the endpoint of their learning.',
        "key_points": [
            'HYROX still evolving rapidly',
            'Fixed knowledge becomes outdated',
            'Growth mindset enables adaptation',
            'Contrast with established sports',
        ],
        "max_pts": 4,
    },
    {
        "number": 4,
        "module": 'M1',
        "qid": 'M1-Q04',
        "question": 'What happens to coaching and athlete development when self-reflection is absent?',
        "primary_answer": "Without self-reflection, a coach's practice stagnates. They continue using methods that may no longer be effective without examining whether they are working. Biases and blind spots go unexamined and unchallenged. The coach fails to adapt to the changing needs of individual athletes. As a result, athlete development is limited not by the athlete's potential but by the ceiling of the coach's unchanged approach.",
        "alternative_answer": 'Coaching without self-reflection becomes repetitive and rigid. The coach keeps doing what they have always done, misses patterns in their own behavior, and stops growing professionally. Athletes suffer the consequences because their development depends on a coach who is not improving.',
        "key_points": [
            'Coaching becomes stagnant',
            'Blind spots go unrecognised',
            'Athlete development limited',
        ],
        "max_pts": 3,
    },
    {
        "number": 5,
        "module": 'M2',
        "qid": 'M2-Q01',
        "question": 'What combination of training types makes HYROX effective for disease prevention and long-term health?',
        "primary_answer": 'HYROX is built around two training modalities: aerobic endurance through running, and functional strength through the eight stations. This combination is significant for health because both types produce adaptations independently supported by research on disease prevention. The running component improves cardiovascular fitness, reduces resting heart rate, and lowers the risk of cardiovascular disease and metabolic disorders. The strength component preserves muscle mass, supports bone density, improves insulin sensitivity, and maintains functional capacity as athletes age. Training both simultaneously makes HYROX more comprehensive for long-term health than single-modality training.',
        "alternative_answer": 'Because HYROX requires both sustained aerobic output and repeated strength-based efforts, it trains the cardiovascular and musculoskeletal systems together. This dual adaptation is what makes it particularly relevant for long-term health and disease prevention, addressing risks that aerobic-only or strength-only training would each address only partially.',
        "key_points": [
            'Combines aerobic and functional strength',
            'Both produce distinct health adaptations',
            'More comprehensive than single-modality',
        ],
        "max_pts": 3,
    },
    {
        "number": 6,
        "module": 'M2',
        "qid": 'M2-Q02',
        "question": 'What is the difference between an acute injury and a chronic overuse injury? Give one running-context example of each.',
        "primary_answer": 'An acute injury occurs suddenly as the result of a specific incident. In a running context, an example is an athlete spraining their ankle by stepping on uneven pavement during an outdoor run. The onset is immediate, with sharp pain and often visible swelling. A chronic or overuse injury develops gradually through repeated loading of a tissue without sufficient recovery time between sessions. In a running context, an example is an athlete developing shin splints or a tibial stress reaction after significantly increasing their weekly mileage without adequate rest periods.',
        "alternative_answer": 'Acute injuries have a clear moment of onset caused by a specific event, such as a muscle strain from misjudging a step during a run. Overuse injuries accumulate over time, like Achilles tendinopathy developing in an athlete who added too much running volume too quickly.',
        "key_points": [
            'Acute: sudden onset, specific incident',
            'Chronic: gradual, repetitive loading',
            'Running example for each',
        ],
        "max_pts": 3,
    },
    {
        "number": 7,
        "module": 'M2',
        "qid": 'M2-Q03',
        "question": 'What is the core message of the HYROX anti-doping module beyond memorising the WADA prohibited list?',
        "primary_answer": 'The core message is that anti-doping is fundamentally a question of what kind of sport HYROX wants to be, not just a compliance exercise. A coach can memorise every substance on the prohibited list and still miss the point. The most important contribution a HYROX coach can make is building a culture in which athletes achieve results through intelligent training, dedication, and integrity. HYROX has the opportunity, as a young sport, to establish itself as a community built on clean competition. Anti-doping is the expression of that commitment.',
        "alternative_answer": 'Knowing the rules matters, but it is not the main point. Anti-doping in HYROX is about building a sport culture that athletes can be proud of, where performance comes from hard work and smart coaching. The prohibited list is the floor, not the ceiling of what this means.',
        "key_points": [
            'About sport culture, not just rules',
            'What kind of sport HYROX wants to be',
            'Build culture of integrity',
        ],
        "max_pts": 3,
    },
    {
        "number": 8,
        "module": 'M2',
        "qid": 'M2-Q04',
        "question": "When an athlete presents with a medical red flag during training, what is the coach's responsibility?",
        "primary_answer": "The coach's responsibility is to stop the training session immediately and refer the athlete to an appropriate medical professional. Red flag symptoms such as chest pain, dizziness, sudden severe injury, loss of sensation, or other signs of a potentially serious underlying condition are outside the coach's scope to assess or treat. Attempting to diagnose, manage, or minimise the situation puts the athlete at risk. The coach's role in this context is clear: recognise that something may be seriously wrong, act promptly to stop loading the athlete, and ensure they receive qualified medical attention.",
        "alternative_answer": "Coaches are not clinicians. When something presents that could be a serious medical issue, the session stops and the athlete goes to a doctor or appropriate professional. The coach's job is to recognise and refer, not to assess and treat.",
        "key_points": [
            'Stop session immediately',
            'Refer to medical professional',
            'Coach does not diagnose or treat',
        ],
        "max_pts": 3,
    },
    {
        "number": 9,
        "module": 'M3',
        "qid": 'M3-Q01',
        "question": 'What is the primary objective of using video analysis in HYROX movement coaching?',
        "primary_answer": 'The primary objective is to enable frame-by-frame review of movement that cannot be observed accurately in real time. Skilled coaches can see a great deal during a live session, but many of the most important technical details happen in fractions of a second. Video allows the coach to pause at any point, examine joint angles, foot placement, and body position precisely, and have an evidence-based technical conversation with the athlete. Video analysis tools also allow measurement of joint angles, comparison of two recordings side by side, and tracking of changes in technique over time.',
        "alternative_answer": 'Video gives coaches access to information they cannot reliably capture with the naked eye during a session. Frame-by-frame review, angle measurement, and side-by-side comparison of recordings over time turn observations into objective technical data that supports more accurate and credible feedback to the athlete.',
        "key_points": [
            'Frame-by-frame review',
            'Angles and timings measurable',
            'Side-by-side comparison possible',
            'Objective basis for feedback',
        ],
        "max_pts": 4,
    },
    {
        "number": 10,
        "module": 'M3',
        "qid": 'M3-Q02',
        "question": 'What three criteria determine whether test data is useful in HYROX athlete assessment?',
        "primary_answer": 'The first criterion is relevance: the test must measure a physical quality that actually matters for HYROX performance. A test that does not connect to race demands tells the coach nothing useful. The second criterion is validity: the test must actually measure what it claims to measure. A test that is sensitive to confounding factors or is poorly designed will not produce accurate information about the quality being assessed. The third criterion is repeatability: the test must be conducted under consistent enough conditions that results from different testing occasions can be meaningfully compared.',
        "alternative_answer": 'Useful test data must be relevant to HYROX performance demands, valid in that it actually measures what it is supposed to measure, and repeatable so that results from one occasion can be compared fairly to results from another. Remove any one of these three and the data loses its value.',
        "key_points": [
            'Relevance',
            'Validity',
            'Repeatability',
        ],
        "max_pts": 3,
    },
    {
        "number": 11,
        "module": 'M3',
        "qid": 'M3-Q03',
        "question": 'Why might a movement limitation in a HYROX athlete be caused by a physical attribute deficiency rather than a technical fault?',
        "primary_answer": "Technical execution depends on the underlying physical capacities that make correct movement mechanically possible. Coaching cues and technical instruction can change how an athlete tries to move, but they cannot create range of motion, strength, or motor control that does not yet exist in the athlete's body. An athlete who lacks the hip mobility required to reach the necessary position in a sandbag lunge will produce a faulty pattern even with perfect coaching, because the joint simply cannot go there. An athlete without sufficient posterior chain strength will not be able to hold the required position in a sled pull under load. Testing physical attributes separately from movement pattern assessment allows the coach to identify whether the root cause requires technical coaching, targeted physical development, or both.",
        "alternative_answer": 'Technique can only be as good as the underlying physical qualities allow. If an athlete cannot move through the required range or lacks the strength to maintain a position under load, coaching cues alone will not fix the pattern. The root cause must be identified first, which requires testing physical attributes separately from observing technique.',
        "key_points": [
            'Technique depends on physical capacity',
            'Coaching cues cannot create missing capacity',
            'Testing identifies root cause',
        ],
        "max_pts": 3,
    },
    {
        "number": 12,
        "module": 'M3',
        "qid": 'M3-Q04',
        "question": 'A coach observes an athlete struggling technically with sandbag lunges. What should the coach assess first, and why?',
        "primary_answer": 'Before coaching a technical correction, the coach should first determine whether the limitation is technical in nature or whether it is rooted in a physical deficiency. This matters because the intervention required for each cause is completely different. To assess this, the coach should observe the movement carefully, ideally using video, and consider whether the athlete has the single-leg strength endurance, glute medius stability, and trunk control that correct execution of the sandbag lunge actually requires. If the athlete lacks the physical foundation for the movement, cueing better technique will have little effect. If the physical capacities are present but the pattern is wrong, technical coaching becomes the priority.',
        "alternative_answer": 'The coach needs to know whether the problem is that the athlete does not know how to do the movement correctly, or that their body does not yet have the physical capacity to do it correctly. These require different interventions, so correctly identifying the root cause before coaching saves time and prevents wasted effort.',
        "key_points": [
            'Physical vs. technical root cause',
            'Video observation used',
            'Single-leg strength, hip stability, trunk control',
            'Different interventions for each cause',
        ],
        "max_pts": 4,
    },
    {
        "number": 13,
        "module": 'M4',
        "qid": 'M4-Q01',
        "question": "Explain the 'Safety, Efficacy, Efficiency' progression as applied to HYROX athlete movement coaching.",
        "primary_answer": 'Safety is the first priority in movement coaching. Before anything else, the athlete must be able to move through the full required range of the movement without pain, compensation, or injury risk. Once safety is confirmed, the focus shifts to efficacy: does the athlete actually meet the movement standard? Are the key positions being reached and the technique correct? Only when the movement is both safe and technically sound does the coaching focus move to efficiency: how can output be maximised and energy cost minimised? Progressing to efficiency before safety and efficacy are established builds performance on a faulty foundation and increases both injury risk and long-term developmental cost.',
        "alternative_answer": 'The order is fixed and non-negotiable. Safety first means the athlete is not at risk of injury. Efficacy means the movement standard is being met. Efficiency means the athlete can now optimise their output from a solid foundation. Skipping steps in this sequence is one of the most common and costly mistakes in strength and conditioning coaching.',
        "key_points": [
            'Safety first: full range, no injury risk',
            'Then efficacy: movement standard met',
            'Then efficiency: output optimised',
            'Order cannot be skipped',
        ],
        "max_pts": 4,
    },
    {
        "number": 14,
        "module": 'M4',
        "qid": 'M4-Q02',
        "question": "What is the 'interference effect' in HYROX training, and how should coaches manage it practically?",
        "primary_answer": 'The interference effect describes how training endurance and strength in the same session or training day can impair the adaptations from strength work. When endurance training precedes strength training, residual neuromuscular fatigue means the athlete cannot generate the intensities needed for effective strength adaptation. The most practically significant form is the acute interference effect within the same day. A practical management strategy is to schedule low-impact conditioning work in the morning and lower body strength training in the afternoon, so that neuromuscular fatigue from the conditioning session has partially dissipated before the strength session begins. Low-impact modes such as cycling are preferable to running before a lower body strength session because they reduce mechanical fatigue on the relevant muscle groups.',
        "alternative_answer": 'When endurance and strength training are both scheduled in the same day, the order and modality of the endurance work matters. Doing it first and choosing a low-impact option like cycling means less fatigue carries into the strength session, allowing the athlete to hit the intensities needed for adaptation.',
        "key_points": [
            'Strength adaptations impaired by prior endurance',
            'Acute effect most practically relevant',
            'Low-impact conditioning in morning',
            'Cycling before lower body strength',
        ],
        "max_pts": 4,
    },
    {
        "number": 15,
        "module": 'M4',
        "qid": 'M4-Q03',
        "question": 'Describe the HYROX 5-Level System and explain one way a coach can use it practically.',
        "primary_answer": 'The 5-Level System is a progressive classification framework that places athletes along a development continuum from beginner through to advanced. Each level defines the movement standards, loading parameters, and physical qualities expected at that stage. It is designed to ensure athletes are appropriately challenged without being overloaded. A coach can use it practically to make progression decisions: rather than advancing an athlete based on time spent in training or their own feeling of readiness, the coach uses the level criteria as an objective benchmark. If the athlete meets the standards for their current level consistently, they are ready to progress. If not, they stay and consolidate before moving on.',
        "alternative_answer": 'The five levels give coaches an objective framework for placing athletes at the right developmental stage and making evidence-based decisions about when to progress them. It prevents both premature loading of athletes who are not yet ready and unnecessary stagnation of athletes who are.',
        "key_points": [
            'Progressive classification beginner to advanced',
            'Defines expected standards per level',
            'Objective progression decisions',
            'Prevents premature loading',
        ],
        "max_pts": 4,
    },
    {
        "number": 16,
        "module": 'M4',
        "qid": 'M4-Q04',
        "question": 'Why is building a strong strength base considered a prerequisite before training power in HYROX?',
        "primary_answer": 'Power is the product of force and velocity: how much force can be applied, and how quickly. An athlete who lacks a solid foundation of maximal strength does not have enough force-producing capacity to generate meaningful power output, regardless of how explosively they move. Power training methods such as plyometrics and Olympic lifting variations require the athlete to already produce substantial force, just at higher speed. Attempting these with insufficient strength is ineffective because the outputs are too low, and potentially injurious because the athlete lacks the structural capacity to manage the loads involved. Building the strength base first creates the raw material that power training then shapes into fast, explosive expression.',
        "alternative_answer": 'You cannot develop power from a weak foundation. Power training asks the athlete to produce force at speed, which requires adequate force capacity to begin with. Without the strength base, power training produces small outputs and carries higher injury risk.',
        "key_points": [
            'Power = force × velocity',
            'Strength base required first',
            'Power training ineffective without it',
            'Higher injury risk without strength base',
        ],
        "max_pts": 4,
    },
    {
        "number": 17,
        "module": 'M5',
        "qid": 'M5-Q01',
        "question": 'What is the stress-recovery-adaptation cycle, and how should a HYROX coach use it to structure training?',
        "primary_answer": 'The stress-recovery-adaptation cycle describes how training produces improvement. Stress is the training load applied: a physiological challenge that exceeds current capacity and disrupts homeostasis. Recovery is the period following the stress during which the body repairs and restores. Adaptation is the result: the body rebuilds to a slightly higher level of capacity than before, better prepared for the next time that stress is encountered. A HYROX coach uses this cycle to structure training by applying sufficient stress to trigger adaptation, then allowing enough recovery time for adaptation to actually occur before the next stress is applied. Applying stress too frequently without adequate recovery leads to overreaching and eventually overtraining. Insufficient stress produces no meaningful adaptation.',
        "alternative_answer": "Training works in a cycle: apply stress, recover, adapt to a higher level. The coach's job is to manage the timing of each phase correctly. Apply stress before the previous adaptation is complete and the athlete breaks down. Apply too little stress or wait too long and the athlete stagnates.",
        "key_points": [
            'Stress: training load exceeds capacity',
            'Recovery: body repairs and restores',
            'Adaptation: capacity rebuilds higher',
            'Sufficient stress and recovery both required',
            'Without recovery: overtraining',
        ],
        "max_pts": 5,
    },
    {
        "number": 18,
        "module": 'M5',
        "qid": 'M5-Q02',
        "question": 'What are the main physiological consequences of exercising in a hot environment for HYROX athletes, and what should coaches monitor?',
        "primary_answer": 'In a hot environment, the body faces a dual demand: it must supply blood to working muscles for exercise and simultaneously divert blood to the skin for cooling. This increases cardiovascular strain, reflected in a higher heart rate at the same exercise intensity compared to a cool environment. Core temperature rises, which if unchecked impairs cognitive and physical performance. Research documents performance reductions of approximately 8 to 12 percent when moving from cool to hot conditions. Dehydration from sweat losses compounds cardiovascular stress by reducing blood volume. Coaches should monitor fluid intake and hydration status, watch for rising perceived exertion disproportionate to actual output, and remain alert for early signs of heat-related illness including confusion, excessive pallor, or cessation of sweating.',
        "alternative_answer": 'The hot environment forces the body to manage two competing demands: fuelling exercise and cooling the body. Heart rate rises, performance drops by roughly 8 to 12 percent, and dehydration makes everything worse. Coaches should track hydration and watch carefully for signs that the athlete is struggling with the heat.',
        "key_points": [
            'Cardiovascular strain increases in heat',
            'Performance drops 8-12% in hot conditions',
            'Dehydration compounds the stress',
            'Monitor hydration and heat illness signs',
        ],
        "max_pts": 4,
    },
    {
        "number": 19,
        "module": 'M5',
        "qid": 'M5-Q03',
        "question": 'What is the principle of supercompensation, and how does it underpin HYROX periodization?',
        "primary_answer": 'Supercompensation describes what happens after a training stress and an adequate recovery period. The body does not simply return to its previous baseline; it rebuilds to a level slightly above it, as a physiological preparation for encountering a similar stress again. If the next training session is timed to fall during this supercompensation window, fitness builds progressively. If the next stress is applied too soon, before adequate recovery, the athlete is training on accumulated fatigue and fitness declines. If it is applied too late, after the supercompensation has subsided, the athlete returns to their previous baseline and no net gain is made. HYROX periodization uses this principle to structure training blocks, recovery periods, and competition preparation phases so that accumulated fitness progresses over time.',
        "alternative_answer": 'Supercompensation means the body adapts above its previous level after stress and recovery. Time the next training session correctly and fitness builds; time it wrong in either direction and the adaptation is wasted. Periodization is the systematic application of this principle across a training year.',
        "key_points": [
            'Body adapts above previous baseline after recovery',
            'Timing the next stress matters',
            'Too early or too late wastes adaptation',
            'Periodization captures supercompensation',
        ],
        "max_pts": 4,
    },
    {
        "number": 20,
        "module": 'M5',
        "qid": 'M5-Q04',
        "question": 'Why is understanding the force-velocity relationship important for training HYROX athletes?',
        "primary_answer": 'The force-velocity relationship describes the fundamental trade-off in muscle mechanics: as the velocity of a contraction increases, the maximal force that can be produced decreases, and vice versa. Heavy, slow lifting occupies one end of the curve, developing maximal strength. Explosive plyometric and speed-based work occupies the other end, developing power at high contraction velocities. Different training methods target different zones along the curve, and each zone produces different adaptations. For HYROX athletes, the implication is that training must span the full curve: heavy strength work for the high-load stations and postural demands, and explosive power work for the dynamic station demands such as the Burpee Broad Jump and explosive starts on the Sled Push. Training only at one end leaves a significant gap.',
        "alternative_answer": 'At high velocity, muscles produce less force. At high force, velocity slows. Different training methods sit at different points on this curve and develop different physical qualities. HYROX athletes need qualities from across the curve, so training must include both heavy and explosive work.',
        "key_points": [
            'High force = slow velocity',
            'High velocity = lower force',
            'Different zones develop different qualities',
            'HYROX needs both ends of the curve',
        ],
        "max_pts": 4,
    },
    {
        "number": 21,
        "module": 'M5',
        "qid": 'M5-Q05',
        "question": 'How does altitude affect HYROX performance, and what does this mean for athletes competing at high-altitude events?',
        "primary_answer": 'At altitude, atmospheric pressure is lower, which means the partial pressure of oxygen in the air is reduced. Each breath delivers less oxygen than at sea level. This reduces the pressure gradient that drives oxygen into the bloodstream, lowering the effective oxygen delivery to working muscles. VO2max and aerobic capacity decline as a result. Performance in endurance-demanding events typically drops in the range of 8 to 12 percent when moving from sea level to hot conditions, with altitude adding further impairment. Athletes who have not acclimatised will experience this reduction immediately. Full acclimatisation requires approximately two to three weeks at altitude. Athletes who travel to high-altitude events without adequate preparation should expect higher perceived effort at the same pace and may consider modified race strategy accordingly.',
        "alternative_answer": 'Altitude reduces the amount of oxygen available per breath. This lowers VO2max and aerobic performance. Athletes who travel to altitude without time to acclimatise will feel the difference immediately. Full adaptation takes around two to three weeks, so travel timing relative to competition matters.',
        "key_points": [
            'Altitude reduces available oxygen per breath',
            'VO2max and aerobic performance decline at altitude',
            'Acclimatisation needed: expect reduced performance until adapted',
        ],
        "max_pts": 3,
    },
    {
        "number": 22,
        "module": 'M6',
        "qid": 'M6-Q01',
        "question": "What is the scope of a HYROX Level 2 coach's role when providing nutrition support, and where are the professional boundaries?",
        "primary_answer": "A HYROX Level 2 coach can provide general nutrition guidance consistent with their qualifications, such as emphasising the importance of hydration, recommending balanced meals that support training, and helping athletes understand the role of carbohydrates and protein in recovery. What falls outside the coach's scope is any form of clinical or individualised nutrition work: creating specific meal plans, prescribing supplements, or managing athletes with eating disorders, gastrointestinal conditions, or medically significant dietary restrictions. These require a registered dietitian or an accredited sports nutritionist. The coach's responsibility is to recognise when an athlete's nutritional needs exceed what a coach can safely address and to make the appropriate referral.",
        "alternative_answer": "General nutrition education is within a coach's role: hydration guidance, the importance of fuelling for training, basic principles of recovery nutrition. Anything clinical or individualised requires referral to a qualified nutrition professional. The boundary is between education and prescription.",
        "key_points": [
            'General guidance within scope',
            'Meal plans and supplements: refer out',
            'Eating disorders, GI, allergies: refer out',
            'Recognise scope limits and refer',
        ],
        "max_pts": 4,
    },
    {
        "number": 23,
        "module": 'M6',
        "qid": 'M6-Q02',
        "question": 'What is the difference between Low Energy Availability (LEA) and Relative Energy Deficiency in Sport (REDs)?',
        "primary_answer": 'Low Energy Availability is a state in which the caloric intake available after accounting for exercise energy expenditure is insufficient to support normal physiological function. The body does not have enough fuel left over for basic biological processes once training demands have been met. This can occur deliberately through caloric restriction or unintentionally when an athlete simply does not eat enough relative to their training volume. Relative Energy Deficiency in Sport is the broader clinical syndrome that develops when LEA is sustained over time. It affects multiple organ systems, producing disruptions to hormonal function, bone health, immune competence, cardiovascular health, and psychological wellbeing. LEA is best understood as the cause, and REDs as the multi-system clinical consequence of prolonged LEA.',
        "alternative_answer": 'LEA is the condition of not having enough energy left over after training. REDs is what happens physiologically when that deficit persists: a multi-system syndrome affecting hormones, bones, immunity, and mental health. One is the input condition, the other is the clinical outcome.',
        "key_points": [
            'LEA: insufficient energy after exercise',
            'LEA can be intentional or unintentional',
            'REDs: multi-system clinical syndrome from sustained LEA',
            'LEA causes; REDs is the consequence',
        ],
        "max_pts": 4,
    },
    {
        "number": 24,
        "module": 'M6',
        "qid": 'M6-Q03',
        "question": 'What are the key nutritional priorities for HYROX race-day fuelling, and how does the hybrid nature of the event complicate standard nutrition strategies?',
        "primary_answer": 'Race-day nutrition for HYROX must support both the sustained aerobic demand of the running segments and the high-intensity anaerobic demands of the eight stations. The three key priorities are: maintaining glycogen availability throughout the race, which requires both pre-race carbohydrate loading and in-race fuelling; sustaining blood glucose stability to prevent energy crashes mid-race; and minimising gastrointestinal distress, which is amplified by the combination of running and explosive station work. The hybrid nature complicates standard nutrition strategies because endurance-focused protocols designed for steady-state running do not account for the repeated explosive outputs at stations, and the physical demands of station work increase the likelihood of GI intolerance compared to pure running.',
        "alternative_answer": 'Standard marathon nutrition does not transfer directly to HYROX. The event demands fuelling for both sustained aerobic effort and repeated explosive work, and the combination of running plus physical exertion makes GI issues more likely. Glycogen management, blood sugar stability, and gut tolerance all need to be addressed together.',
        "key_points": [
            'Maintain glycogen availability',
            'Sustain blood glucose stability',
            'Minimise GI distress',
            'Standard endurance fuelling does not cover stations',
            'Running plus stations increases GI risk',
        ],
        "max_pts": 5,
    },
    {
        "number": 25,
        "module": 'M6',
        "qid": 'M6-Q04',
        "question": "What is the 'food first' principle in HYROX supplementation guidance, and when might supplementation be justified?",
        "primary_answer": 'The food first principle holds that nutrients should be obtained from whole foods in preference to supplements wherever possible. Whole food sources provide nutrients in their natural matrix alongside other beneficial compounds, and the evidence base for whole food nutrition in supporting performance and health is stronger than for isolated supplements. Supplementation may be justified in three specific circumstances: when training and competition demands make it genuinely difficult to meet certain nutrient needs through diet alone; when a documented deficiency exists as a result of dietary restriction or medical condition; or when a specific ergogenic aid has robust evidence of safety and effectiveness. Before recommending any supplement to an athlete, the coach should verify all three dimensions: that it is safe, that there is good evidence for its effectiveness, and that it is permitted under WADA anti-doping rules.',
        "alternative_answer": 'Food first means whole food nutrition before supplements. Supplementation is justified when dietary intake genuinely cannot meet requirements, when a deficiency is documented, or when an evidence-based ergogenic aid is appropriate. Safety, efficacy, and anti-doping compliance must all be verified before any supplement is recommended.',
        "key_points": [
            'Food first principle',
            'Supplementation justified for documented deficiency',
            'Justified when diet cannot meet needs',
            'Safety, efficacy, WADA compliance required',
        ],
        "max_pts": 4,
    },
    {
        "number": 26,
        "module": 'M6',
        "qid": 'M6-Q05',
        "question": 'Why does energy availability matter specifically for HYROX female athletes, and what signs should a coach monitor?',
        "primary_answer": 'Female athletes in HYROX face elevated risk of LEA, particularly during high-volume training periods. When energy availability drops below the threshold required for normal physiological function, the first systems affected are those considered non-essential for survival, including reproductive function and bone metabolism. Sustained LEA in female athletes can cause menstrual irregularities or the complete loss of menstrual function, reduced bone density increasing the risk of stress fractures, disruptions to hormonal function, immune suppression, mood disturbances, and cognitive impairment. Coaches should monitor for: unexplained underperformance or persistent fatigue, irregular or absent menstrual cycles, recurrent bone stress injuries, and changes in mood, concentration, or motivation. Any of these signs should prompt a referral to medical and nutritional professionals rather than an attempt to manage the situation within the coaching relationship.',
        "alternative_answer": 'Female athletes are particularly vulnerable to LEA during heavy training. The consequences include menstrual disruption, stress fractures from reduced bone density, immune suppression, and mood changes. Coaches should watch for these signs and refer to appropriate professionals when they appear.',
        "key_points": [
            'Female athletes at elevated LEA/REDs risk',
            'Watch for menstrual irregularities',
            'Watch for stress fractures',
            'Watch for fatigue and mood changes',
            'Refer to medical/nutritional professionals',
        ],
        "max_pts": 5,
    },
    {
        "number": 27,
        "module": 'M7.1',
        "qid": 'M7.1-Q01',
        "question": "What does 'racing literacy' mean in HYROX, and how does it go beyond physical fitness?",
        "primary_answer": 'Racing literacy is the ability of an athlete to read the race as it unfolds, correctly interpret what those conditions and constraints mean for their performance decisions, adapt their behavior in real time based on that interpretation, and then actually execute those decisions while under physical and psychological stress. An athlete who is physically well prepared but racing-illiterate may still make costly errors: going out too hard, failing to recognise when a tactical shift is needed, or losing their race plan when conditions do not match their expectations. Racing literacy is a cognitive and tactical dimension of performance that must be developed alongside physical preparation, not assumed to emerge from fitness alone.',
        "alternative_answer": 'Racing literacy is the tactical and cognitive side of competing: reading what is happening, understanding what it means, adjusting your behaviour, and executing under fatigue and pressure. It is not a product of fitness; it is a separate trainable skill that must be coached specifically.',
        "key_points": [
            'Read race as it unfolds',
            'Interpret constraints and conditions',
            'Adapt behaviour in real time',
            'Execute under fatigue and pressure',
            'Separate skill from physical fitness',
        ],
        "max_pts": 5,
    },
    {
        "number": 28,
        "module": 'M7.1',
        "qid": 'M7.1-Q02',
        "question": "What is the 'Funnel of Variability' and how should a HYROX coach use it in skill development?",
        "primary_answer": 'The Funnel of Variability, introduced by Newcombe in 2021, is a framework for structuring how training variability and competition-specific pressure are increased as athletes develop. At the narrow entry point of the funnel, training environments are highly structured, predictable, and controlled, which is appropriate for novice athletes who are building foundational skills and need consistency to establish technique. As athletes progress, the funnel widens: training introduces more variability in conditions, constraints, and demands, gradually closing the gap between practice and competition. The coach uses the funnel as a guide for knowing how much variability and race-like pressure is appropriate at each stage of development, preventing the common mistake of either keeping advanced athletes in controlled environments too long or exposing novices to complexity before they have the foundations.',
        "alternative_answer": 'The Funnel of Variability is a progression model for training complexity. Beginners need structured, predictable environments. Advanced athletes need exposure to variability and race-like pressure. The funnel describes how and when to shift between these, ensuring the athlete is always challenged at the right level.',
        "key_points": [
            'Framework: progressively increases training variability and complexity',
            'Narrow end: structured and predictable for novices',
            'Widens with variability as athlete develops',
            'Calibrate complexity to developmental stage',
        ],
        "max_pts": 4,
    },
    {
        "number": 29,
        "module": 'M7.1',
        "qid": 'M7.1-Q03',
        "question": "How should a HYROX coach identify the 'sweet spot' for skill learning for an individual athlete?",
        "primary_answer": "The sweet spot is located at the upper boundary of what the athlete can currently accomplish independently: the point where the challenge requires the athlete to stretch beyond their existing capacity but remains achievable with appropriate coaching support. To identify it for a specific athlete, the coach assesses the athlete's current independent performance level across the relevant skill dimensions: technical execution, tactical decision-making, and performance under fatigue. The sweet spot is found where the athlete must work, makes errors that generate learning rather than failure, and can make meaningful progress with guidance. It is individual: what is the sweet spot for one athlete is too easy or too hard for another. It also shifts upward as the athlete develops, requiring the coach to continuously reassess rather than assume a fixed challenge level remains appropriate.",
        "alternative_answer": 'To find the sweet spot for an individual athlete, the coach assesses where that athlete currently operates independently, then designs tasks that sit just above that level. The athlete should be stretched, should make mistakes that produce learning, and should be able to progress with support. This point is different for every athlete and moves as they improve.',
        "key_points": [
            'Just beyond current independent ability',
            'Errors drive learning',
            'Individual to each athlete',
            'Must be reassessed as athlete develops',
        ],
        "max_pts": 4,
    },
    {
        "number": 30,
        "module": 'M7.2',
        "qid": 'M7.2-Q01',
        "question": 'Why is the hip and core described as the primary power source when running, rather than the legs?',
        "primary_answer": "In running and virtually all other dynamic sports requiring power, the force that drives movement originates from the body's mid-section: the hips and core. The limbs, including the arms and legs, function primarily as transmitters of that centrally generated force rather than as primary generators. The hips extend and drive the movement forward; the leg swings through and the arms move in a coordinated pattern that follows from the hip motion rather than initiating it. This principle is not unique to running: the same central-to-peripheral power generation is seen in kicking a football, throwing a punch, or lifting a barbell from the floor. Coaches who understand this teach their athletes to initiate running power from hip extension, with relaxed arms that transfer rather than fight against the generated movement.",
        "alternative_answer": 'Power in running comes from the hips and core. The legs and arms transmit that force outward. This is consistent across all dynamic sports: hip drive generates the power, and the limbs channel it. Coaches who teach athletes to run from their hips get better power output with less energy waste in the periphery.',
        "key_points": [
            'Hips and core generate primary force',
            'Arms and legs transmit force',
            'Consistent across dynamic sports',
            'Teach running from hip extension',
        ],
        "max_pts": 4,
    },
    {
        "number": 31,
        "module": 'M7.2',
        "qid": 'M7.2-Q02',
        "question": 'Why is running technique coaching using static demonstrations at the front of a group considered problematic?',
        "primary_answer": 'Running is a cyclical, dynamic movement that happens at speed. The most important technical concepts involve the relationship between body position and ground at the moment of contact, which unfolds in fractions of a second. Static demonstrations at the front of a group cannot show this. When a coach demonstrates foot placement statically, they typically show where the foot should end up relative to the body while both are stationary. This often inadvertently suggests the athlete should place the foot in front of themselves, which is precisely the error that produces overstriding. The actual coaching concept is that the foot should be moving backward relative to the ground at the moment of contact, which can only be understood through video or dynamic demonstration in motion, not through a static pose.',
        "alternative_answer": 'Static demonstrations freeze a movement that only makes sense in motion. The key concept in running mechanics, that the foot moves backward relative to the ground at contact, cannot be shown while standing still. Static demos often reinforce the wrong mental model and produce the errors they are trying to prevent.',
        "key_points": [
            'Running is dynamic, not static',
            'Static demos create incorrect mental models',
            'Foot-ground relationship invisible statically',
            'Use video and dynamic demonstration',
        ],
        "max_pts": 4,
    },
    {
        "number": 32,
        "module": 'M7.2',
        "qid": 'M7.2-Q03',
        "question": 'For a HYROX athlete who trains high running volume, what specific risks must their coach monitor and manage?',
        "primary_answer": 'High running volume in HYROX athletes carries specific risks that compound with the station training already in the program. First, overuse injuries to the connective tissues most loaded by running: Achilles tendinopathy, tibial stress injuries, patellar tendinopathy, and stress fractures of the tibia or metatarsals. Second, biomechanical breakdown under fatigue: as the athlete tires across a long run or heavy training week, running form deteriorates and injury risk increases. Third, strength imbalances from running dominance: athletes who run a lot without adequate strength work develop relative weaknesses in posterior chain and hip stabiliser capacity. Fourth, total load overaccumulation: adding high running volume on top of an already significant station training load can push total physiological stress beyond recovery capacity. The coach must monitor weekly training load, check for asymmetries, and ensure running is balanced with strength and mobility work.',
        "alternative_answer": 'High running volume alongside station training creates cumulative load risk. Watch for overuse injuries in tendons and bone, form breakdown in tired sessions, strength imbalances from running dominance, and total load exceeding what the athlete can recover from.',
        "key_points": [
            'Risk: overuse injuries (Achilles, tibial, stress fractures)',
            'Risk: biomechanical breakdown under fatigue',
            'Risk: strength imbalances',
            'Risk: total load overaccumulation',
            'Monitor and balance all components',
        ],
        "max_pts": 5,
    },
    {
        "number": 33,
        "module": 'M7.3',
        "qid": 'M7.3-Q01',
        "question": 'What is Off-Feet Conditioning in HYROX, and what is the primary piece of equipment used?',
        "primary_answer": 'Off-Feet Conditioning refers to cardiovascular training that does not involve running or lower-body impact loading. In the HYROX context it is built primarily around the Wattbike, a performance cycling ergometer that generates precise, repeatable power output data in watts. The rationale for OFC is that running places cumulative mechanical stress on the joints, tendons, and bones of the lower body. By substituting some running-based conditioning with Wattbike work, athletes can maintain or develop cardiovascular fitness while reducing that structural loading. This is particularly valuable during rehabilitation, during high training load phases where additional running would push structural demand beyond recovery capacity, and for athletes managing chronic lower-body niggles.',
        "alternative_answer": 'Off-Feet Conditioning is cardiovascular training without the impact load of running. In HYROX it is primarily done on the Wattbike. It allows athletes to develop their aerobic and anaerobic fitness while giving the joints, tendons, and bones a break from running-related mechanical stress.',
        "key_points": [
            'Non-impact cardiovascular conditioning',
            'Primary tool: Wattbike',
            'No running mechanical stress',
            'Valuable for rehab, high load, injury management',
        ],
        "max_pts": 4,
    },
    {
        "number": 34,
        "module": 'M7.3',
        "qid": 'M7.3-Q02',
        "question": 'What are the advantages of off-feet training for athletes managing lower-body injuries or high running loads?',
        "primary_answer": 'For an injured athlete, the primary challenge is maintaining cardiovascular fitness while allowing the damaged structure to recover. The cardiovascular system begins to detrain relatively quickly without stimulus, but the injured structure requires reduced mechanical loading to heal. The bike resolves this tension: it delivers a meaningful cardiovascular stimulus through cycling, a low-impact modality that places minimal stress on most running-related injury sites. The athlete stays aerobically fit without aggravating the injury. For athletes managing high running loads, adding more running volume to increase conditioning risks pushing structural demand beyond recovery capacity. Substituting some running sessions with bike work adds cardiovascular volume without adding running-related structural load, keeping total training stress higher without increasing overuse injury risk.',
        "alternative_answer": 'Injured athletes need to keep their aerobic fitness without stressing the injured structure. The Wattbike solves this. For athletes already at high running volume, it adds cardiovascular training without adding the structural load that causes overuse injuries.',
        "key_points": [
            'Cardiovascular fitness without mechanical stress',
            'Cardiovascular system detrains quickly',
            'Injured structures need relative rest',
            'Adds volume without overuse risk',
        ],
        "max_pts": 4,
    },
    {
        "number": 35,
        "module": 'M7.3',
        "qid": 'M7.3-Q03',
        "question": 'What is leg-speed development on the Wattbike and why is it relevant for HYROX running performance?',
        "primary_answer": 'Leg-speed development involves performing bike intervals at high cadence with low resistance. The training stimulus targets the neuromuscular patterns responsible for rapid limb cycling: the rate at which the nervous system can coordinate the leg muscles to complete each pedal cycle. This neural adaptation transfers to running by supporting a higher running cadence, meaning more steps per minute at the same pace. A higher running cadence, in turn, tends to reduce overstriding and braking forces because shorter, more frequent strides naturally land the foot closer to beneath the center of mass. The bike is an ideal tool for this work because the low-impact environment removes the injury risk associated with equivalent high-speed running intervals, allowing higher volumes of cadence training to be accumulated safely.',
        "alternative_answer": 'High-cadence, low-resistance bike work trains the nervous system to cycle the legs faster. This transfers to running as a higher step rate, which reduces overstriding and braking forces. It is a safe way to develop the neuromuscular patterns behind faster running turnover.',
        "key_points": [
            'High cadence, low resistance',
            'Trains neuromuscular firing for rapid cycling',
            'Transfers to higher running cadence',
            'Reduces overstriding and braking forces',
        ],
        "max_pts": 4,
    },
    {
        "number": 36,
        "module": 'M7.4',
        "qid": 'M7.4-Q01',
        "question": 'For the SkiErg station, what movement pattern should athletes use and what physical qualities are key to develop?',
        "primary_answer": 'Athletes should perform the SkiErg using a hip hinge pattern, not a squat. Each stroke begins with the hips hinging back and loading, then driving forward and down, with the latissimus dorsi initiating the pull of the handles at the catch phase. The error commonly seen is athletes squatting with each stroke, which reduces power per stroke and is inefficient over the full station distance. The three key physical qualities to develop are: anterior chain strength including the lats, abdominals, and hip flexors which drive the hip hinge pull; trunk stiffness through exercises such as pallof press, ab rollouts, and long plank holds, which allow force to transfer efficiently through the core without energy loss; and power endurance, the capacity to maintain stroke power throughout the full station duration.',
        "alternative_answer": 'SkiErg performance is built on a hip hinge, not a squat. The lats initiate the pull and the hips drive the stroke. The physical foundation needs anterior chain strength for the pulling force, trunk stiffness for efficient force transfer, and power endurance to sustain output across the full station.',
        "key_points": [
            'Hip hinge, not a squat',
            'Lats initiate the pull',
            'Anterior chain strength required',
            'Trunk stiffness required',
            'Power endurance required',
        ],
        "max_pts": 5,
    },
    {
        "number": 37,
        "module": 'M7.4',
        "qid": 'M7.4-Q02',
        "question": 'For the Sled Pull, what fundamental technique principle applies from the deadlift, and which muscle group is critical?',
        "primary_answer": 'The key deadlift principle that carries over directly to the Sled Pull is keeping the arms long throughout the movement. In the Sled Pull the arms should function as extensions of the rope, transmitting force from the body to the sled without bending at the elbow to create additional mechanical advantage. Any early arm bend reduces the efficiency of force transfer and causes unnecessary fatigue in the biceps and forearms at the expense of the larger posterior chain muscles that should be doing the work. The posterior chain, comprising the glutes and hamstrings primarily, is the critical muscle group. The movement should be driven by hip extension, with the legs and hips generating force from the floor while the arms remain long as the connection point between body and rope.',
        "alternative_answer": 'The deadlift principle is to keep the arms straight and treat them as extensions of the rope rather than as levers. The work should come from the posterior chain driving through hip extension. Bending the arms early shifts effort to the smaller muscles of the upper arm, reducing power transfer and increasing fatigue.',
        "key_points": [
            'Arms long: extension of the rope',
            'Early arm bend reduces efficiency',
            'Posterior chain drives through hip extension',
            'Glutes and hamstrings are primary movers',
        ],
        "max_pts": 4,
    },
    {
        "number": 38,
        "module": 'M7.4',
        "qid": 'M7.4-Q03',
        "question": "Why is the Farmers Carry described as a 'postural endurance' challenge rather than just a grip test?",
        "primary_answer": "While grip strength is a genuine limiting factor in the Farmers Carry, the systemic limiter across the full race distance is the athlete's ability to maintain postural integrity under load while moving at speed. The upper traps prevent the loaded kettlebells from dragging the shoulders downward. The middle traps anchor the shoulder blade and provide the stable base from which the arms can hold the load. The obliques and rectus abdominis maintain trunk stiffness and prevent lateral lean and rotation. The spinal erectors keep the back from rounding under the accumulated loading and movement demands. When any of these fail, the athlete's posture collapses, energy is lost through the body rather than transferred into forward movement, and pace drops. Grip fails locally; postural breakdown affects the entire system.",
        "alternative_answer": 'Grip matters but the real performance limiter across the full Farmers Carry is whether the athlete can keep their whole body upright and stable under load while moving fast. Every postural failure in the traps, core, and spinal erectors costs forward pace. Grip is one link in the chain; postural endurance is the chain itself.',
        "key_points": [
            'Postural endurance across kinetic chain',
            'Upper and middle traps',
            'Obliques and spinal erectors',
            'Postural collapse = energy leakage and pace loss',
        ],
        "max_pts": 4,
    },
    {
        "number": 39,
        "module": 'M7.4',
        "qid": 'M7.4-Q04',
        "question": "How does an athlete's squat mechanics and posture affect Wall Ball accuracy and consistency across 100 repetitions?",
        "primary_answer": 'The accuracy and height of each Wall Ball throw is directly determined by the consistency of the squat mechanics from which the throw is generated. The squat provides the loading phase that stores energy for the throw; the launch angle and power of the throw are products of how the athlete rises out of the squat. If squat depth, stance width, or trunk position varies between repetitions, the throw output varies accordingly. As upper back posture breaks down under fatigue, the elbows drift forward and downward, which shifts the ball position and the direction of force at release. The ball begins to project at a lower, more oblique angle rather than cleanly upward, and target accuracy suffers. The front squat is the most specific training exercise because it closely replicates the upper body demands of the Wall Ball catch position, building the squat endurance and upper back strength needed to maintain form through the final repetitions.',
        "alternative_answer": 'Every throw comes from the squat. If the squat varies, the throw varies. As upper back fatigue causes the elbows to drop and the chest to round, the ball position shifts and the throw angle drops. Keeping consistent squat mechanics and upper body posture through all 100 repetitions is the technical challenge of Wall Balls.',
        "key_points": [
            'Consistent squat mechanics = consistent throw',
            'Stance, depth, trunk position all matter',
            'Postural breakdown disrupts throw angle',
            'Front squats build required endurance',
        ],
        "max_pts": 4,
    },
    {
        "number": 40,
        "module": 'M8',
        "qid": 'M8-Q01',
        "question": 'What is periodization in HYROX coaching, and why is it more complex than in a single-modality sport?',
        "primary_answer": 'Periodization is the systematic organisation of training over time into structured phases, each with defined training emphases, loads, and recovery periods, designed to bring the athlete to peak performance at the right moment. In a single-modality sport like marathon running or powerlifting, the coach is optimising one primary physical quality and building their training plan around that. In HYROX, the coach must simultaneously develop endurance, strength, power, speed, coordination, and flexibility for eight stations plus running. These qualities sometimes interfere with each other when trained together, have different optimal training stimuli, and have different rates of development and residual duration. Bringing all of them to peak condition simultaneously on race day requires more sophisticated planning than optimising for one quality alone.',
        "alternative_answer": 'Periodization is structured training planning that organises load, recovery, and competition preparation over time. In HYROX it is more complex than in single-modality sports because multiple physical qualities must all peak simultaneously, and some of them interfere with each other when trained together.',
        "key_points": [
            'Systematic planning: stress, recovery, competition',
            'HYROX: multiple competing qualities',
            'Interference between qualities',
            'All must peak simultaneously',
        ],
        "max_pts": 4,
    },
    {
        "number": 41,
        "module": 'M8',
        "qid": 'M8-Q02',
        "question": "What does 'athlete monitoring' involve in HYROX Level 2 coaching, and why is it essential?",
        "primary_answer": 'Athlete monitoring is the systematic collection and analysis of data that describes how an athlete is responding to training over time. The three main domains are training load, which includes volume and intensity; performance metrics, which include race times, split data, strength tests, and Wattbike outputs; and subjective wellbeing indicators, which include reported sleep quality, fatigue, mood, and motivation. Monitoring is essential in HYROX because athletes come from highly diverse sporting backgrounds and respond very differently to the same training program. Monitoring allows the coach to identify early when an athlete is accumulating fatigue beyond their recovery capacity, when a training block is not producing the expected adaptations, and when an athlete is ready to progress rather than simply following a predetermined schedule.',
        "alternative_answer": 'Monitoring means systematically collecting data on training load, performance metrics, and subjective wellbeing to understand how the athlete is actually responding to training. In HYROX it is essential because diverse athlete backgrounds produce very different responses to the same program.',
        "key_points": [
            'Covers load, performance metrics, wellbeing',
            'Diverse backgrounds = different responses',
            'Identifies fatigue accumulation early',
            'Enables proactive adjustments',
        ],
        "max_pts": 4,
    },
    {
        "number": 42,
        "module": 'M8',
        "qid": 'M8-Q03',
        "question": "What is 'double peaking' in periodization, and why might a HYROX coach structure a macrocycle around two performance peaks?",
        "primary_answer": 'Double peaking is the deliberate structuring of a training year to produce two separate periods of peak performance within the same season. Athletes who target two significant events, for example an early-season race and an end-of-season championship, need to peak for both rather than building toward only one. Peak form is a temporary physiological state: it represents maximal fitness with minimal accumulated fatigue, achieved through a taper phase. This state cannot be maintained indefinitely, as the reduction in training that produces freshness also gradually reduces fitness if continued too long. Double peaking requires a precise timing of two taper phases, each preceded by a distinct preparation block, with a recovery and rebuilding phase between the two peaks to allow the athlete to retrain before the second peaking cycle.',
        "alternative_answer": 'Two events requiring peak performance in one season means two peaking cycles. Each peak needs its own preparation block and taper. Between them, the athlete must recover and rebuild before starting the second cycle. The challenge is that peak form is temporary, so timing both peaks correctly requires precise planning.',
        "key_points": [
            'Two planned performance peaks per season',
            'Each needs preparation and taper',
            'Recovery and rebuild between peaks',
            'Peak form is temporary',
            'Timing must be precise',
        ],
        "max_pts": 5,
    },
    {
        "number": 43,
        "module": 'M8',
        "qid": 'M8-Q04',
        "question": 'What does research suggest about the relationship between training variables and HYROX race performance?',
        "primary_answer": 'Research including work by Brant and colleagues published in 2025 has identified strong correlations between endurance training volume and HYROX completion times, suggesting that athletes who accumulate more aerobic training tend to perform better in the race. Heart rate and blood lactate data collected during HYROX racing confirm that both aerobic and anaerobic metabolic pathways are significantly engaged, supporting the case for developing both systems. However, HYROX is a novel sport and the research base is still developing. The specific relative contributions of strength, power, station-specific skill, and different training variables to race performance remain under-researched. Current evidence justifies a periodized approach that prioritises endurance volume while also developing strength and power across the training year.',
        "alternative_answer": 'Early research shows endurance training volume is closely linked to HYROX performance. Race physiology confirms both aerobic and anaerobic systems are heavily used. HYROX is still young as a sport and much of the training science specific to it remains to be developed.',
        "key_points": [
            'Endurance volume correlates with race times',
            'Both aerobic and anaerobic pathways engaged',
            'HYROX research still emerging',
            'Periodize endurance and strength/power',
        ],
        "max_pts": 4,
    },
    {
        "number": 44,
        "module": 'M9',
        "qid": 'M9-Q01',
        "question": 'What is Self-Determination Theory and how does it help HYROX coaches understand athlete motivation?',
        "primary_answer": 'Self-Determination Theory, developed by Ryan and Deci in 2000, is a psychological framework that explains why people are motivated to engage with activities over the long term. It identifies three types of motivation: amotivation, in which the person has no motivation and sees no value in the activity; extrinsic motivation, in which behaviour is driven by external rewards, recognition, or the avoidance of punishment; and intrinsic motivation, in which the person is driven by genuine interest, enjoyment, and personal meaning. SDT also identifies three basic psychological needs whose satisfaction is necessary for genuine engagement: autonomy, the sense of personal choice and agency; competence, the feeling of being capable and effective; and relatedness, the experience of meaningful connection with others. For HYROX coaches, SDT provides a framework for designing environments and interactions that move athletes toward intrinsic motivation, which is the most sustainable and health-promoting form.',
        "alternative_answer": "SDT explains that motivation exists on a spectrum from no motivation through external motivation to genuine internal motivation. The most sustainable and health-supporting form is intrinsic. Coaches use SDT to design training environments that meet athletes' needs for autonomy, competence, and connection, which cultivates intrinsic motivation rather than dependence on external rewards.",
        "key_points": [
            'Three motivation types: amotivation, extrinsic, intrinsic',
            'Three needs: autonomy, competence, relatedness',
            'Intrinsic motivation most sustainable',
            'Coaching builds intrinsic motivation',
        ],
        "max_pts": 4,
    },
    {
        "number": 45,
        "module": 'M9',
        "qid": 'M9-Q02',
        "question": "What is the difference between a 'challenge state' and a 'threat state' in HYROX competition, and what determines which one an athlete experiences?",
        "primary_answer": 'A challenge state occurs when an athlete appraises the demands of a situation as manageable given their available resources: their preparation, skills, and physical readiness. In this state, physiological activation feels energising and performance tends to be enhanced. A threat state occurs when perceived demands exceed perceived resources: the situation feels overwhelming, the activation is experienced as anxiety rather than readiness, and performance is typically impaired. The critical insight from research is that both states involve the same underlying physiological arousal. The difference is entirely determined by cognitive appraisal: how the athlete interprets the situation relative to their resources. Coaches can shift athletes from threat to challenge by building genuine competence through preparation, using pre-performance routines to establish a sense of control, and teaching athletes to reinterpret physiological activation as a sign of readiness rather than danger.',
        "alternative_answer": 'Challenge and threat states involve identical physiological arousal. The difference is in how the athlete interprets it. Perceived resources matching or exceeding demands produces a challenge state. Perceived demands exceeding resources produces threat. Coaching can shift athletes toward challenge by building competence, establishing routines, and teaching reappraisal.',
        "key_points": [
            'Challenge: perceived resources meet demands',
            'Threat: perceived demands exceed resources',
            'Same physiological arousal, different interpretation',
            'Determining factor: cognitive appraisal',
        ],
        "max_pts": 4,
    },
    {
        "number": 46,
        "module": 'M9',
        "qid": 'M9-Q03',
        "question": "What does it mean to 'simulate pressure' in HYROX training, and why is a standard full-course simulation often insufficient?",
        "primary_answer": "Pressure simulation means creating training conditions that replicate the psychological and environmental stressors of competition, not just the physical demands of the workout. A full-course simulation in a familiar gym with known training partners and no stakes attached replicates the physical experience of HYROX but not the psychological one. On race day, the environment is unfamiliar, the crowd is present, the outcome carries real significance, and unexpected things happen. The brain scans for novelty and threat, and the athlete must perform while managing that activation. A gym simulation does not train this. True pressure simulation introduces elements that activate the athlete's stress response: unfamiliar venues, observers, time pressure, unexpected changes to the session, or small consequences attached to performance. Only by training decision-making and execution under these conditions does the athlete develop the mental adaptability that race day demands.",
        "alternative_answer": 'A standard simulation trains physical capacity in a familiar, safe environment. Race day is none of those things. True pressure simulation introduces the psychological stressors of competition: unfamiliar environments, observers, real stakes, unexpected changes. The goal is to train mental adaptability, not just physical execution.',
        "key_points": [
            'Pressure = psychological + environmental stressors',
            'Gym simulation is physically but not psychologically real',
            'True simulation activates stress response',
            'Trains mental adaptability, not just execution',
        ],
        "max_pts": 4,
    },
    {
        "number": 47,
        "module": 'M9',
        "qid": 'M9-Q04',
        "question": 'How is the concept of neurodiversity relevant to HYROX coaching, and how should coaches adjust their approach for neurodivergent athletes?',
        "primary_answer": "Neurodiversity is the recognition that human brains are naturally wired in different ways. Conditions such as ADHD, autism spectrum conditions, and hypersensitivity are not deficits to be corrected but expressions of cognitive and sensory diversity. In HYROX coaching, neurodivergent athletes may experience challenges with sustained attention during complex multi-step sessions, sensory overwhelm in busy competition environments, difficulty with ambiguous or inconsistent communication, or the social demands of training in groups. They may also bring significant strengths including intense focus on specific areas, high motivation, and unconventional problem-solving. Coaches should adapt their communication to be clearer and more structured, be mindful of the sensory environment in training, avoid framing neurodivergent traits as problems to be managed, and refer to specialist support when the athlete's needs go beyond coaching competence.",
        "alternative_answer": 'Different brains work differently. Neurodivergent athletes may find certain aspects of training environments or communication harder, and others easier. Coaches should adapt their communication style, consider the sensory demands of the training environment, and treat cognitive differences as variation rather than deficiency.',
        "key_points": [
            'Natural brain variation, not deficit',
            'Challenges: attention, sensory overload, social demands',
            'Adapt communication and structure',
            'Recognise strengths in neurodivergent profiles',
            'Refer when beyond coaching competence',
        ],
        "max_pts": 5,
    },
    {
        "number": 48,
        "module": 'M10',
        "qid": 'M10-Q01',
        "question": 'What defines a junior HYROX athlete, and why must coaches treat them differently from scaled-down adult athletes?',
        "primary_answer": "The junior HYROX athlete is defined as a 16 to 18 year old who is transitioning toward adulthood but has not yet completed that transition. They are not a scaled-down adult in any meaningful physiological, cognitive, or psychological sense. Physically, they may still be growing, with developing skeletal structures and growth plates that respond differently to loading than mature adult tissue. Cognitively, decision-making capacity, emotional regulation, and risk assessment are still developing. Psychologically, this is a formative period for identity, confidence, and the athlete's long-term relationship with sport. Programming must apply Long-Term Athlete Development principles to protect growth structures, avoid premature specialisation, and develop physical literacy. The coach's role extends far beyond fitness: the most important outcome of working with a junior athlete is that they leave each session more confident, more capable, and more connected to their sport than when they arrived.",
        "alternative_answer": "Junior athletes are 16 to 18 and still developing physically, cognitively, and psychologically. They need LTAD-informed programming that protects growth structures and avoids premature loading. More importantly, the coach's job is to build the whole person: confidence, belonging, and a positive long-term relationship with sport matter as much as fitness.",
        "key_points": [
            '16-18: still developing physically, cognitively, psychologically',
            'Not scaled-down adults',
            'LTAD principles for programming',
            'Build confidence, belonging, sport relationship',
            'Fitness is not the only coaching focus',
        ],
        "max_pts": 5,
    },
    {
        "number": 49,
        "module": 'M10',
        "qid": 'M10-Q02',
        "question": 'What are the key female-specific health domains HYROX Level 2 coaches should be aware of when coaching female athletes?',
        "primary_answer": "The five key domains are: the menstrual cycle, which produces hormonal fluctuations across its phases that influence training tolerance, recovery capacity, and injury risk; bone health, where female athletes face elevated risk of stress fractures and osteoporosis, particularly when energy availability is compromised; Low Energy Availability and the risk of developing REDs, the multi-system clinical syndrome caused by sustained LEA; pelvic floor health, which is relevant in the high-impact and high-load movements of HYROX including running, jumps, and heavy carries; and life-stage factors including pregnancy, the postpartum return to training, and the physiological changes of perimenopause. The coach's role across all five domains is awareness and appropriate referral. Clinical assessment and management of any of these conditions requires specialist medical or allied health support.",
        "alternative_answer": "Five domains matter: the menstrual cycle's effect on training, bone health and stress fracture risk, LEA and REDs, pelvic floor health under HYROX loading, and life-stage factors like pregnancy and perimenopause. The coach's role in all five is awareness and referral, not clinical management.",
        "key_points": [
            'Menstrual cycle affects training tolerance and recovery',
            'Bone health and stress fracture risk',
            'LEA and REDs',
            'Pelvic floor under HYROX loading',
            'Life-stage factors',
            'Awareness and referral only',
        ],
        "max_pts": 6,
    },
    {
        "number": 50,
        "module": 'M10',
        "qid": 'M10-Q03',
        "question": 'What are the main physiological changes with aging in masters HYROX athletes, and how should training be adapted to account for them?',
        "primary_answer": 'The primary age-related physiological changes include: a progressive decline in VO2max of approximately one percent per year after age 35, reflecting reduced aerobic capacity; sarcopenia, the age-related loss of muscle mass and specifically of fast-twitch fiber proportion, which reduces strength and power output; a decline in tendon elasticity that reduces the passive elastic contribution to running power; longer recovery times between high-intensity sessions as the regenerative capacity of tissue slows; and an increased cardiovascular risk profile that makes screening and graduated intensity progression more important. Training adaptations should directly address each of these: maintaining high-intensity work to counteract VO2max decline; prioritising strength training to combat sarcopenia; including progressive tendon loading and plyometric work to preserve elastic capacity; allowing longer recovery windows; and ensuring current medical clearance is in place.',
        "alternative_answer": 'Masters athletes face declining VO2max, muscle loss, reduced tendon elasticity, slower recovery, and increased cardiovascular risk. Training must counter each of these: keep high-intensity work to maintain aerobic capacity, prioritise strength to preserve muscle, use plyometrics to maintain tendon elasticity, allow longer recovery, and ensure medical screening.',
        "key_points": [
            'VO2max and aerobic capacity decline with age',
            'Sarcopenia reduces muscle mass and power',
            'Tendon elasticity declines, recovery takes longer',
            'Training: maintain intensity, prioritise strength and plyometrics',
        ],
        "max_pts": 4,
    },
    {
        "number": 51,
        "module": 'M10',
        "qid": 'M10-Q04',
        "question": "What three coaching pillars define the 'complete high-performance HYROX coach' according to Module 10?",
        "primary_answer": 'The three pillars are Programming and Science, Empathy, and Expert in the Sport. Programming and Science refers to evidence-based training design: understanding the physiological and biomechanical demands of HYROX, key performance metrics including lactate threshold, critical power, and vVO2max, and how to translate that knowledge into effective training programs. Empathy means genuinely understanding the athlete as a person: their motivations, life circumstances, emotional state, and individual needs, and adjusting the coaching relationship accordingly. Expert in the Sport means deep HYROX-specific knowledge: race strategy and tactics, station mechanics, competition structure, athlete profiling within the sport, and the evolving evidence base specific to HYROX. A coach who is strong in two pillars but weak in the third will be limited in ways that become apparent in high-performance contexts.',
        "alternative_answer": 'Three pillars define complete high-performance coaching. Science and programming knowledge provides the technical foundation. Empathy builds the relationship and adapts the coaching to the individual. Sport expertise provides deep HYROX-specific knowledge. A coach missing any one of these three has a gap that will show under pressure.',
        "key_points": [
            'Three pillars: Programming/Science, Empathy, Expert in Sport',
            'Programming: evidence-based design',
            'Empathy: understand athlete as person',
            'Expert: deep HYROX-specific knowledge',
            'Deficiency in any one limits effectiveness',
        ],
        "max_pts": 5,
    },
    {
        "number": 52,
        "module": 'M10',
        "qid": 'M10-Q05',
        "question": 'What considerations are most important when coaching an adapted HYROX athlete, and what has historically limited the evidence base in this area?',
        "primary_answer": "Adapted athletes have a wide range of physical, neurological, sensory, and functional presentations. Each presentation affects how the athlete produces force, tolerates fatigue, thermoregulates, experiences the psychological demands of competition, and is at risk of specific injury patterns. The coaching approach must be individualised to the athlete's specific impairment type and functional presentation rather than applied generically. Movement modifications may be necessary at some or all stations. The evidence base for coaching adapted athletes in performance sport has historically been limited because most research on injury prevention, training adaptation, and performance development has been conducted in able-bodied populations or in small, highly specialised elite Paralympic cohorts. This research does not always translate to the broad and diverse population of adapted HYROX athletes. Coaches should apply general principles with care, recognise the boundaries of their specific impairment knowledge, and refer to specialists when those boundaries are reached.",
        "alternative_answer": 'Adapted athletes are diverse. Each impairment type affects force production, fatigue tolerance, thermoregulation, and injury risk differently. The evidence base is limited because most research comes from able-bodied populations or elite Paralympic athletes, neither of which maps cleanly to the broad adapted HYROX population. Coaches must individualise, apply caution, and refer when their impairment-specific knowledge runs out.',
        "key_points": [
            'Diverse impairment types affect force, fatigue, thermoregulation',
            'Movement modifications may be needed',
            'Evidence base from able-bodied/Paralympic populations',
            'Does not always transfer to HYROX',
            'Individualise and refer when knowledge runs out',
        ],
        "max_pts": 5,
    },
]

# Module keys in fixed assessment order (M1..M10, with M7 split into 7.1-7.4).
MODULES: list[str] = [
    'M1',
    'M2',
    'M3',
    'M4',
    'M5',
    'M6',
    'M7.1',
    'M7.2',
    'M7.3',
    'M7.4',
    'M8',
    'M9',
    'M10',
]

TOTAL_QUESTIONS = len(QUESTIONS)
TOTAL_MAX_POINTS = sum(q["max_pts"] for q in QUESTIONS)

# Index by question number for O(1) lookups by the backend state engine (results.py).
QUESTIONS_BY_NUMBER: dict[int, AssessmentQuestion] = {q["number"]: q for q in QUESTIONS}

# Ordered question numbers per module, and each module's maximum points.
MODULE_QUESTIONS: dict[str, list[int]] = {m: [q["number"] for q in QUESTIONS if q["module"] == m] for m in MODULES}
MODULE_MAX_POINTS: dict[str, int] = {
    m: sum(QUESTIONS_BY_NUMBER[n]["max_pts"] for n in nums) for m, nums in MODULE_QUESTIONS.items()
}


def get_question(number: int) -> Optional[AssessmentQuestion]:
    """Return the question with this 1..52 number, or None if unknown."""
    return QUESTIONS_BY_NUMBER.get(number)


def key_point_count(number: int) -> int:
    """How many required key points question ``number`` has (== expected length of the per-point verdict)."""
    q = QUESTIONS_BY_NUMBER.get(number)
    return len(q["key_points"]) if q else 0


def max_points(number: int) -> int:
    """The point cap for question ``number`` (0 if unknown)."""
    q = QUESTIONS_BY_NUMBER.get(number)
    return q["max_pts"] if q else 0


def module_of(number: int) -> str:
    """The module key for question ``number`` ("" if unknown)."""
    q = QUESTIONS_BY_NUMBER.get(number)
    return q["module"] if q else ""


def module_label(module_key: str) -> str:
    """'M7.1' -> 'Module 7.1' (learner-facing module heading)."""
    return "Module " + module_key.lstrip("M") if module_key else ""


def module_questions(module_key: str) -> list[int]:
    """Ordered question numbers in ``module_key`` (empty if unknown)."""
    return list(MODULE_QUESTIONS.get(module_key, []))


def module_max_points(module_key: str) -> int:
    """Maximum points available in ``module_key`` (0 if unknown)."""
    return MODULE_MAX_POINTS.get(module_key, 0)


def module_index(module_key: str) -> int:
    """0-based position of ``module_key`` in the fixed order (-1 if unknown)."""
    return MODULES.index(module_key) if module_key in MODULES else -1


def is_last_module(module_key: str) -> bool:
    """True when ``module_key`` is the final module of the assessment."""
    return bool(MODULES) and module_key == MODULES[-1]


def next_module(module_key: str) -> Optional[str]:
    """The module after ``module_key`` in fixed order, or None if it is the last/unknown."""
    idx = module_index(module_key)
    if idx < 0 or idx + 1 >= len(MODULES):
        return None
    return MODULES[idx + 1]
